apiVersion: v1
kind: Service
metadata:
  name: postgrest
  namespace: supabase
spec:
  selector:
    app: postgrest
  ports:
    - port: 3000
      targetPort: 3000
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: gotrue
  namespace: supabase
spec:
  selector:
    app: gotrue
  ports:
    - port: 9999
      targetPort: 9999
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: realtime
  namespace: supabase
spec:
  selector:
    app: realtime
  ports:
    - port: 4000
      targetPort: 4000
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: storage
  namespace: supabase
spec:
  selector:
    app: storage
  ports:
    - port: 8080
      targetPort: 8080
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: supabase-minio
  namespace: supabase
spec:
  selector:
    app.kubernetes.io/name: minio
  ports:
    - port: 9000
      targetPort: 9000
  type: ClusterIP
